print("Date: 05.18.2022")
print("Weather report: 13 degrees C")
print("Time: 10:34")
print("group A")
print("course name: Introduction to CS")
print("branch name: Feature1")
n = int(input("Your age: "))
print(n)
z = input("Your Zodiac Sign: ")
print(z)
print("Technical Issue status: not resolved yet")
